### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/ksl-header#34]
After working with a fellow developer to submit a change to ksl-header, I think it would be good to add a CONTRIBUTING.md to explain how to submit changes to ksl-header whether you have write permission, or need to fork the project.

We should also mention what needs to happen after merging the pull-request:

+ [Tag a Release](https://github.com/deseretdigital-ui/ksl-header/releases/new)
+ `gulp ghpages`
+ notify teams that are using the ksl-header.

**Comment by janiv** [comment]
See #45

**Comment by janiv** [comment]
Fixed in #75
