### ISSUE TITLE
Can't scroll page using keyboard

### ISSUE THREAD

**Issue by formigone** [deseretdigital-ui/ksl-header#36]
Please make it so the header widget passes scroll events on to the rest of the page somehow.

When [page loads](http://stage-v2.ksl.com/?sid=32487512&nid=1322 for live example) you can't scroll using the keyboard (arrow keys, space bar, page up/down, etc.). If you press tab so that the header widget is focused, you still can't scroll with the keyboard. If the mouse pointer is over the header, you can't scroll using the mouse wheel. Only way to scroll with keyboard is if you unfocus the header (clicking another element or tabbing away from it). Same with mouse wheel.

**Comment by jehoshua02** [comment]
Please submit issue on ddm-menu project and link these issues together.

**Comment by jehoshua02** [comment]
@formigone I take it back. Before doing anything else, can you reproduce the issue at either of these links?

+ ddm-menu demo page: http://ui.deseretdigital.com/ddm-menu/
+ ksl-header demo page: http://ui.deseretdigital.com/ksl-header/

If not, go through the [ksl-header README.md](https://github.com/deseretdigital-ui/ksl-header) make sure no detail was missed.

The link to the [page](http://stage-v2.ksl.com/?sid=32487512&nid=1322%20for%20live%20example) you included doesn't seem to work at all.

**Comment by formigone** [comment]
@jehoshua02 The bug happens on both of those pages, as described in my original explanation. I'm running Chrome 40.0.2214.93 (64-bit) on Ubuntu. Bug is also present in Firefox 35.0.1 for Ubuntu.

The link included is an internal KSL beta page, so you must be connected to the DDM network.

**Comment by jehoshua02** [comment]
Since you were able to reproduce the issue on the ddm-menu, my guess the root of the problem is there.

I was able to reproduce these issues on the ddm-menu demo page. I'm going to spend a little time to see what can be done and let you know.

**Comment by jehoshua02** [comment]
Done.

**Comment by formigone** [comment]
Good job, and thanks for your hard work on this!
